# Generated by Django 4.2.7 on 2023-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_userquestion_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_response',
            field=models.CharField(choices=[('1', 'Time Value of Money'), ('2', 'Annuities'), ('3', 'Loans'), ('4', 'Bonds'), ('5', 'Other')], default='Other', max_length=1),
        ),
    ]
