# Generated by Django 4.2.7 on 2023-12-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_question_correct_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('1', 'Time Value of Money'), ('2', 'Annuities'), ('3', 'Loans'), ('4', 'Bonds'), ('5', 'Other')], default='Other', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_response',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], default='A', max_length=1),
        ),
    ]
